### ISSUE TITLE
Ensure translations work fine

### ISSUE THREAD

**Issue by mauryaratan** [analogwp/analogwp-templates#330]
- Create a new installation with a separate language
- Create new translated po/mo with base file to match that language, just add a couple strings to ensure translation works
- Current setup is most likely not working, so please see other plugin examples if needed. Gutenberg repository itself would be nice place to start digging.
- Ideally, it should be `setLocaleData` from `wp.i18n` package, but do inspect.

**Comment by mauryaratan** [comment]
@lushkant what's the status on this?

**Comment by lushkant** [comment]
our current build produces ang.js pot which is not right and is made for the source files not the actual one we use which is app.js

btw ram you can see some of the stuff i pushed in feature/330_fix_translations  > https://github.com/mauryaratan/analogwp-templates/blob/feature/330_fix_translation/

it also includes some changes in webpack config to not loose i18n methods in the app.js
but it essentially increases the resulting file size, since I also had to turn off mangle for similar reasons.
