### ISSUE TITLE
Upload template media files inside designated folder

### ISSUE THREAD

**Issue by mauryaratan** [analogwp/analogwp-templates#371]
Currently, any images imported from templates/blocks are directly uploaded in the media library. Let's change that so all images are categorized with template ids inside a designated folder. Here's what it may look like:

- `uploads/style-kits`
  - `template-11-120-hash`
  - `template-12-240-hash`

Where `11` is site ID, `120` is Post ID, and `hash` is a unique generated string during import.

This makes cleanup easier if/when users decide to remove Style Kits plugin and also gives them an idea of what came from our plugin.

**Comment by gvgvgvijayan** [comment]
After analyzing the image import logic I believe that the file structure (template-11-120-hash) is not possible due to the following reasons

### Post ID

The post id is generated after the media is uploaded. 

In Elementor class **Import_Images**: 
[Elementor wp_upload_bits call](https://github.com/elementor/elementor/blob/master/includes/template-library/classes/class-import-images.php#L119) occur before attachment [post creation](https://github.com/elementor/elementor/blob/master/includes/template-library/classes/class-import-images.php#L139) 

The same problem is applicable for our plugin class **Import_Images**:
[Analog wp_upload_bits](https://github.com/analogwp/analogwp-templates/blob/develop/inc/class-import-image.php#L157) occur before attachment [post creation](https://github.com/analogwp/analogwp-templates/blob/develop/inc/class-import-image.php#L177)

### Hash

The hash generation also mapped after the creation of Image and Image's post  i.e. WP attachment post

Elementor source link: [Image hash mapping to the attachment post](https://github.com/elementor/elementor/blob/master/includes/template-library/classes/class-import-images.php#L144)

Analog source link: [Image hash mapping to the attachment post](https://github.com/analogwp/analogwp-templates/blob/develop/inc/class-import-image.php#L181)


### Current Implementation's Result
![issue_371_a0827af](https://user-images.githubusercontent.com/4319097/86357927-3cd11480-bc8c-11ea-9f06-743089c00d03.png)


### Suggestion

While exploring the three AJAX calls (Templates, Style Kits, and Blocks Imports) found that all these three commonly passing the following parameters in the request

1. id
2. site_id (In template & style kit import parameter named as site_id and in blocks named as siteID)
3. title

so shall we make use of these values and suffix it like this **mediaName_(id)_(site_id)_hash(title).jpg** or else as we noted both in Elementor & Analog the hash generated using the remote URL so shall we make naming convention in remote URL itself to make media's name unique.

@mauryaratan kindly share your thoughts

**Comment by mauryaratan** [comment]
Hey @gvgvgvijayan,

Thanks for looking into it.

Here's what my initial thoughts are:

- The filename itself doesn't matter, it can be what it currently is. What I meant with `template-11-120-hash` is a folder name.
- So if you were to import a template or a block, it would create a new folder called `template-11-120-hash`, for blocks `block-11-120-hash`. Parameters should be the same as suggested originally, `siteID`, `postID`, and a unique hash. 
- All the images for that import would go under this same folder.

**Comment by gvgvgvijayan** [comment]
@mauryaratan I will check that.

**Comment by gvgvgvijayan** [comment]
1. When import occurs in code
2. Apply a filter on a hook that fires up when an image is uploaded
3. Read that image attachment, and check for `_elementor_source_image_hash` or `_analog_image_hash`
4. If true, add that post ID to a new options object
5. Remove the filter once we’re finished importing

**Comment by lushkant** [comment]
This is no longer a requirement, let's close this!
