### ISSUE TITLE
Admin: Style Kit Edit With Elementor

### ISSUE THREAD

**Issue by gvgvgvijayan** [analogwp/analogwp-templates#387]
![Edit with elementor](https://user-images.githubusercontent.com/4319097/84512912-4ba85500-ace6-11ea-973f-30a8ca2ec814.png)

In style kits admin page, there is no direct row action to do "edit with elementor" so shall we can add an action link as like in elementor template admin page. See image for visual interpretation.

**Comment by JohnPixle** [comment]
Thanks for the input here @gvgvgvijayan , actually this link was there a few versions earlier but we decided to remove this intentionally because it was confusing to users:

When a user would click to _edit with Elementor_ any of the available Style Kits, he didn't actually see any layout in the editor, only the Theme Styles panel would open, but no ability to preview any changes made. This UX was a bit confusing so we decided to remove the link.

Cheers!
