### ISSUE TITLE
Redesign Blocks Library

### ISSUE THREAD

**Issue by mauryaratan** [analogwp/analogwp-templates#393]
Please redesign the Blocks library as per the [mockup](https://www.figma.com/file/WewTsQAjGvzRQahddcH0KK6m/Product-UI?node-id=1286%3A9808).

The idea is to have a new button to launch blocks library inside the editor. This should be a new React app, not part of existing app.

![image](https://user-images.githubusercontent.com/1505631/87363309-82e07f00-c58e-11ea-9a31-9e6a0618db7f.png)
Notice the 4th icon here.

#### To do
- [x] Create a new dir `/client/blocks-library` and everything should live under.
- [x] Add a new menu submenu to Style Kits (temporary), React app should exist on that page only, not on main library page.
- [x] *Upgrade to Style Kits Pro* text in bottom left is supposed to be a carousel of preset messages. Could be a simple CSS animation.

#### Instructions
- Let's use Gutenberg components as much as we can. 
- Refer to [SK UI](https://www.figma.com/file/kOdprBRtF7VB8hzWASXRx9/SK-UI-2?node-id=21%3A833) in figma for popup design and more.

**Comment by mauryaratan** [comment]
https://github.com/analogwp/block-screenshots now makes use of full automation. The trigger has been added to https://github.com/mauryaratan/preview.analogwp.com

You can make use of this URL format: `https://bs.analogwp.com/1000.jpg` where 1000 is post ID for the block. Note that this only applies for blocks, not templates or style kits.

**Comment by gvgvgvijayan** [comment]
1. The **star icon** is showing **black color** instead of **golden-yellow** color
![star-icon](https://user-images.githubusercontent.com/4319097/88295536-2d893800-cd1b-11ea-8135-e6fc455b0b5c.png)
2. The **number of argument**  in the function call is **more** than a function declaration:
**Called:** https://github.com/analogwp/analogwp-templates/blob/feature/393_redesign_blocks_library/client/blocks-library/BlocksLibrary.js#L51
**Declaration:** https://github.com/analogwp/analogwp-templates/blob/feature/393_redesign_blocks_library/client/blocks-library/BlocksLibrary.js#L62
3. Replace **“popularityIndex”** to **“published”**:
**Condition:** https://github.com/analogwp/analogwp-templates/blob/feature/393_redesign_blocks_library/client/blocks-library/BlocksLibrary.js#L83

**Comment by JohnPixle** [comment]
The blocks library is very good so far
3 things I see:

1. The sidebar must be sticky (both in dashboard and the editor. You can scroll very long down in some cases.
2. Change text into  Upgrade to Style Kits Pro and remove the fade animation.
3. The individual block boxes behaviour should be similar to the template kits boxes and how they respond to viewport width.

![Screenshot 2020-07-30 at 13 59 42](https://user-images.githubusercontent.com/4193672/88916122-2d82be00-d26e-11ea-8b66-0aa73c89244d.png)









Hm, and number 4: there are no indicators of free / pro in the blocks, I will look into it

**Comment by JohnPixle** [comment]
Additionally to the above, there are two more things:

 1. I think the sidebar categories look better with 14px font size.
![Screenshot 2020-08-05 at 17 26 44](https://user-images.githubusercontent.com/4193672/89425095-3f1e0700-d741-11ea-8d63-a959dff68145.png)

2. I believe that we must have a consistent UI for marking the favourites. Instead of having the star here next to import, can we have the same hover effect where the star appears on the top left in a blue triangle? No need for the white overlay effect over the image, I think we need just the triangle.

![Screenshot 2020-08-05 at 17 34 03](https://user-images.githubusercontent.com/4193672/89425616-e733d000-d741-11ea-88a1-5a838c5af246.png)

let me know for any Questions.

**Comment by JohnPixle** [comment]
Ok guys, as per slack, this is what we need to do to the blocks library before releasing the update:

Instead of having the blocks library in a dedicated page / popup, let's consolidate it as a tab to the main library, as the screenshot below shows.

![Screenshot 2020-08-06 at 18 29 25](https://user-images.githubusercontent.com/4193672/89554573-b920bf80-d817-11ea-8ec6-18d7ff8c59bb.png)


So there **must not** be an additional page in the SK settngs.

![Screenshot 2020-08-06 at 19 06 56](https://user-images.githubusercontent.com/4193672/89554805-056bff80-d818-11ea-821e-f1b75126b5e6.png)

@gvgvgvijayan please also note that the boxes and hovers have changed. We are using now a unified look. Please make these changes and let's see those deployed

**Comment by lushkant** [comment]
@gvgvgvijayan I'll be taking care of these 🥇
