### ISSUE TITLE
Get_plugins() call conflicts with other plugins having similar calls

### ISSUE THREAD

**Issue by gvgvgvijayan** [analogwp/analogwp-templates#396]
https://github.com/analogwp/analogwp-templates/issues/394

**Comment by lushkant** [comment]
Hey @gvgvgvijayan 
As Ram said - https://github.com/analogwp/analogwp-templates/pull/397#issuecomment-661725319

We cannot use active_plugins hook to check for plugins because we need to check if the plugin is installed first then do activate messages as well.

In the upcoming WP 5.5, there is a REST endpoint which gives us an option to check installed plugins, we can utilize this here as a resolve for our current situation.

![image](https://user-images.githubusercontent.com/18240138/88141167-acde1500-cc10-11ea-891b-d6339b097da7.png)

Take a look here for more info on this - https://make.wordpress.org/core/2020/07/16/new-and-modified-rest-api-endpoints-in-wordpress-5-5/ 

Let me know if you have any questions 😃

**Comment by gvgvgvijayan** [comment]
Hi @lushkant

Rest API will not be a backward compatible one but we can use this in the near future.

**Comment by lushkant** [comment]
@gvgvgvijayan I've left some comments in your last commit, please go through them when you can 😄
