### ISSUE TITLE
SK + Whte Label CMS

### ISSUE THREAD

**Issue by JohnPixle** [analogwp/analogwp-templates#406]
As a user reported, some styles get missing when users create custom welcome screens using SK. More info in the ticket.
[Helpscout link](https://secure.helpscout.net/conversation/1248269489/5201/)

cc @mauryaratan

**Comment by gvgvgvijayan** [comment]
@JohnPixle I looked into the Help Scout, the self-sign in link it redirects to WP limited access dashboard. I opened a single page it don't have "edit with elementor" menu in the top admin bar. So I can't able view what's user saying. Can I create a local environment with the plugin https://wordpress.org/plugins/white-label-cms/ and test the same?

**Comment by mauryaratan** [comment]
@gvgvgvijayan That's perfectly fine V. Whatever we can at our end :)

**Comment by gvgvgvijayan** [comment]
> @gvgvgvijayan That's perfectly fine V. Whatever we can at our end :)

Ok, The reason why I'm asked is when we heeded to page there is no menu for "edit with elementor" in the admin bar and I thought the plugin "White Label CMS" is restricting the installed plugin based on the user who logged in. That's why the user shared link in help scout not showing elementor as a result the page don't have the menu "Edit with elementor" in admin bar.

**Comment by JohnPixle** [comment]
Ok, I guess there is not much we can do here, I am closing this issue.
