### ISSUE TITLE
Changed background and accent classes and nothing changed

### ISSUE THREAD

**Issue by Ostii** [analogwp/analogwp-templates#447]
This section was `sk-dark-bg`. When it was changed to `sk-light-gb` none of the font colors changed.

![Style_Kits](https://user-images.githubusercontent.com/5764507/96946877-488f6200-152d-11eb-89c5-1bce9afd4842.jpg)

![Style_Kits_-_Class_Update](https://user-images.githubusercontent.com/5764507/96947283-7b862580-152e-11eb-8251-88215d1c3c3e.jpg)

**Comment by gvgvgvijayan** [comment]
@Ostii share the public URL of this page.

**Comment by Ostii** [comment]
Hey @gvgvgvijayan 
https://castlemainecoworking.com.au/

I've created a new section to demonstrate it. It is the second section on the page.
When I change it from dark to light, the font still stayed white.
Maybe when sk-light-bg is the class, the font color is supposed to stay white, but even when I delete the class from the section the font stays white.

Let me know if you need logins to WP.

![Elementor___Home](https://user-images.githubusercontent.com/5764507/97062996-24915680-15e9-11eb-9c5c-9c2414114007.jpg)

**Comment by gvgvgvijayan** [comment]
@Ostii Kindly check in Style Kits "Background Color Classes" panel's tab what color is set for controls `Background Color`, `Text Color` & `Headings Color` and try to change it to make font color as contrast as possible.

**Comment by gvgvgvijayan** [comment]
![Light Class](https://user-images.githubusercontent.com/4319097/107194090-9fa23f80-6a15-11eb-937c-b77a476993bc.png)
![Dark Class](https://user-images.githubusercontent.com/4319097/107194106-a29d3000-6a15-11eb-861f-0d70edb83d3c.png)

Tested by creating a section and applied both `sk-light-bg` and `sk-dark-bg` with accent color element both primary and secondary accent. All the color values are applied for the respective element properly.

@Ostii we hope the issue was resolved for you, If it's not resolved could you please update the plugin to the latest and check. Thank you for your patience and detailed explanation about the issue.
